language: dart

dart:
  - dev

dart_task:
  - test: --enable-experiment=non-nullable --platform vm
  - test: --enable-experiment=non-nullable --platform chrome
  - dartanalyzer: --enable-experiment=non-nullable --fatal-warnings --fatal-infos .

matrix:
  include:
    - dart: dev
      dart_task: dartfmt

# Only building master means that we don't run two builds for each pull request.
branches:
  only: [master, null_safety]

cache:
  directories:
    - $HOME/.pub-cache
